### ISSUE TITLE
Unable to load world with LootTweak Script in effect

### ISSUE THREAD

**Issue by JasonMcRay** [Darkhax-Minecraft/LootTableTweaker#1]
I have a simple script to remove chest loot pools. But whenever I try to join to existing or new world, my minecraft freezes and does not continue. If I remove the script it works fine.

Here is a part of the log from the time when it happens: https://www.dropbox.com/s/q9krp2zfrdqj8in/latest.log?raw=1

And here is the sript used: https://www.dropbox.com/s/6eg2k47gwsaa7ta/sgcraft.zs?raw=1

**Comment by Darkhax** [comment]
I've isolated the actual crash from your report, so I can look into it later on today. This is very weird, and I am guessing it's a bug introduced by forge backporting changes from 1.12. 

```
[20:30:47] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.LootTableLoadEvent@29748404:
java.lang.RuntimeException: Attempted to modify LootPool after being frozen!
	at net.minecraft.world.storage.loot.LootPool.checkFrozen(LootPool.java:98) ~[ban.class:?]
	at net.minecraft.world.storage.loot.LootPool.removeEntry(LootPool.java:116) ~[ban.class:?]
	at net.darkhax.lttweaker.LTTMod.onTablesLoad(LTTMod.java:101) ~[LTTMod.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_342_LTTMod_onTablesLoad_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
```

**Comment by Darkhax** [comment]
After looking at the forge log, something is very off here. You're using this mod on 1.10.2, however this mod was included in several modpacks which definitely did not have this issue. Did you place the script in the right folder? It doesn't go in the normal scripts folder, it goes in a sub folder. `/scripts/LootTableTweaker/`. If you are, then it's likely another mod causing the loot tables to load at an inappropriate time.

**Comment by JasonMcRay** [comment]
Yup I have it in the subfolder. Thing is I remember having LTT with exactly same script in past and it was working just fine. Today I relaunched my pack to continue some work on it, no changes done at all since last time, and it stopped working.

**Comment by TheQKnight** [comment]
I'm having the same issue, its in the right folder and everything

**Comment by Darkhax** [comment]
@TheQKnight Which version are you using? Things have changed for 1.12+, if you're using a newer version could you create a new issue with your exact info?
