### ISSUE TITLE
Item still spawning after being removed from loot tables.

### ISSUE THREAD

**Issue by GlitchOG** [Darkhax-Minecraft/LootTableTweaker#10]
LTT version:1.1.17
Forge: 2795
Minecraft 1.12.2

This is the script https://pastebin.com/ykQzdAqJ , now as the wiki says i named my script "LootTableTweaker"

and some of the items still spawn like the ender io gears and the capacitors etc, also i still get the ic2 ingots to spawn. i tested this spawning dungeon chests to see what loot to remove and it still spawns over and over and over. i even tried removing the ore using the oredict method as you can see in the script.

**Comment by Darkhax** [comment]
Thanks for the report, my mod is kind of trash tbh. I would recommend using another mod like https://minecraft.curseforge.com/projects/loottweaker until I can properly fix it.
