### ISSUE TITLE
Removing items from all loot tables ?

### ISSUE THREAD

**Issue by Thyriel** [Darkhax-Minecraft/LootTableTweaker#2]
Hi,

i'm just trying to get behind on how to tweak my loottables, works great so far.
But there's one thing i'm not sure if there would be an easier way of doing it.
For example i want to remove all <minecraft:iron_sword> from ALL loottables. Is there any way to define the table i'm altering to be all loot tables or is the only way by calling every single loottable and removing it seperatly from each table ?

**Comment by Darkhax** [comment]
This snip should work for you. 
```
mods.ltt.LootTable.removeGlobalItem("itemid");
```
