### ISSUE TITLE
Removed items from all loottables but enchanted versions still in chests

### ISSUE THREAD

**Issue by Thyriel** [Darkhax-Minecraft/LootTableTweaker#3]
Hi,

i removed all kind of stuff from all loottables, but it seems a lot enchanted versions are still to be found in dungeon chests.

Script:
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_pickaxe");
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_shovel");
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_axe");
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_sword");
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_hoe");
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_ingot");

Log:
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: LootTableTweaker\removevanilla.zs}
[INITIALIZATION][CLIENT][INFO] Added loot removal for Global Item: minecraft:iron_pickaxe
[INITIALIZATION][CLIENT][INFO] Added loot removal for Global Item: minecraft:iron_shovel
[INITIALIZATION][CLIENT][INFO] Added loot removal for Global Item: minecraft:iron_axe
[INITIALIZATION][CLIENT][INFO] Added loot removal for Global Item: minecraft:iron_sword
[INITIALIZATION][CLIENT][INFO] Added loot removal for Global Item: minecraft:iron_hoe
[INITIALIZATION][CLIENT][INFO] Added loot removal for Global Item: minecraft:iron_ingot

Is this a bug or do i need to specify more parameters in the script ?

edit: Or could it be that these chests from roguelike dungeons mod don't use the loottable system ?

**Comment by Darkhax** [comment]
Looking at their wiki, they do not use loot tables, and have their own loot format.
