### ISSUE TITLE
Is this supposed too happen ?

### ISSUE THREAD

**Issue by Adarcer** [Darkhax-Minecraft/LootTableTweaker#5]
in console -------
[16:31:29] [main/INFO]: [CHAT] ERROR: [crafttweaker | SIDE_CLIENT]: Error parsing LootTableTweaker\Loottable.zs:13 -- ; expected
Script up too erroring line----------
import mods.ltt.LootTable;
//examples
//mods.ltt.LootTable.removeTable("table"); - Removes a specific table.
//mods.ltt.LootTable.removePool("table", "pool"); - Removes a specific pool.
//mods.ltt.LootTable.removeEntry("table", "pool", "entry"); - Removes a specific entry.
//mods.ltt.LootTable.removeItem("table", "pool", "itemid"); - Removes a specific item.
//mods.ltt.LootTable.removeModEntry("modid"); - Removes all entries added by a mod.
//mods.ltt.LootTable.removeModItem("modid"); - Removes all items added by a mod.
//mods.ltt.LootTable.removeModTable("modtable"); - Removes all tables added by a mod.
//mods.ltt.LootTable.removeGlobalItem("itemid"); - Removes this item from all tables.

//Tools
mods.ltt.LootTable.removeGlobalItem("extrautils2:sickle_stone");

**Comment by Darkhax** [comment]
The error CraftTweaker is giving seems wrong, but I believe you need to use the brackets. <extrautils2:sickle_stone>.

**Comment by Adarcer** [comment]
Kind of confused on what you mean do you mean like this ?
mods.ltt.LootTable.removeGlobalItem("<extrautils2:sickle_stone>");

**Comment by Adarcer** [comment]
ok will try that let you know if it work... well that works it needed the greater/less then brackets If i knew this i could have left them in instead of editing them out :P... thanks for the quick reply

**Comment by Darkhax** [comment]
In CraftTweaker scripts, Items go in brackets. 

```
mods.ltt.LootTable.removeGlobalItem(<extrautils2:sickle_stone>);
```
