### ISSUE TITLE
[1.12] Crash on Game Start

### ISSUE THREAD

**Issue by MasterEnderman** [Darkhax-Minecraft/LootTableTweaker#6]
Crash-Report: https://pastebin.com/q8cdF9Uu
Forge: 14.23.1.2606
CraftTweaker: 4.1.0
LootTableTweaker: 1.1.13
JEI: 4.8.5.147

Script (is in /scripts/LootTableTweaker/):
```
mods.ltt.LootTable.removeGlobalItem("minecraft:iron_ingot");
```

**Comment by Bulldog83** [comment]
I have same problem on 1.12.2 dedicated server.
https://gist.github.com/Bulldog83/0aeb3c3b7d078cca74eff52eaf65b89a

**Comment by Darkhax** [comment]
Sorry for taking so long to respond, it seems a bunch of issues from February didn't get to me. I put out a fix a few moments ago which should fix this issue. If it does not, please let me know and I will respond much sooner.
